name: CI-compile

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git zip gawk

    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow

    - name: Get version
      id: version
      run: echo "::set-output name=version::$(make oplversion)"

    - name: Compile -> make clean release
      run: |
        make --trace clean release
        mv OPNPS2LD-*.ZIP OPNPS2LD.ZIP

    - name: Upload release artifact
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: OPNPS2LD
        path: OPNPS2LD.ZIP

    - name: Create detailed changelog
      run: sh ./make_changelog.sh

    - name: Upload changelog for variants artifact 
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: OPNPS2LD-VARIANTS
        path: |
          DETAILED_CHANGELOG
          CREDITS
          LICENSE
          README.md

  build-variants:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    strategy:
      matrix:
        rtl: ["", RTL=1]
        pademu: ["", PADEMU=1]
        igs: ["", IGS=1]
        t10k: ["", DTL_T10000=1]
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git

    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow

    - name: Get version
      id: version
      run: echo "::set-output name=version::$(make oplversion)"

    - name: Compile -> make ${{ matrix.t10k }} ${{ matrix.igs }} ${{ matrix.pademu }} ${{ matrix.rtl }} NOT_PACKED=1
      run: |
        make --trace ${{ matrix.t10k }} ${{ matrix.igs }} ${{ matrix.pademu }} ${{ matrix.rtl }} NOT_PACKED=1
        mv opl.elf OPNPS2LD-${{ matrix.t10k }}-${{ matrix.igs }}-${{ matrix.pademu }}-${{ matrix.rtl }}-${{ steps.version.outputs.version }}.ELF

    - name: Upload variants artifact
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: OPNPS2LD-VARIANTS
        path: |
          OPNPS2LD*.ELF

  create-release:
    needs: [build, build-variants]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Download release artifact
      uses: actions/download-artifact@v1
      with:
        name: OPNPS2LD

    - name: Download variants artifact
      uses: actions/download-artifact@v1
      with:
        name: OPNPS2LD-VARIANTS

    - name: Prepare artifacts for release
      run: |
        mv OPNPS2LD OPNPS2LD-LATEST.ZIP
        7z a -t7z OPNPS2LD-VARIANTS-LATEST.7z OPNPS2LD-VARIANTS/*

    - name: Create release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Latest development builds"
        files: |
          OPNPS2LD-LATEST.ZIP
          OPNPS2LD-VARIANTS-LATEST.7z
 
